### ISSUE TITLE
No free software license

### ISSUE THREAD

**Issue by nfitzen** [Jorkoh/LiveSplit.Minecraft#1]
This project doesn't seem to have a license, and therefore [people can't legally use it](https://choosealicense.com/no-permission/#for-users).

Would you consider adding a free software license? I noticed that there's only 1 code contributor to the repo, so it shouldn't be too complicated to add one.

If you want a recommendation, I'd say [`GPL-3.0-or-later`](//spdx.org/licenses/GPL-3.0-or-later.html) is a good choice, but other options include [`MIT`/Expat](//spdx.org/licenses/MIT.html) or [`Apache-2.0`](//spdx.org/licenses/Apache-2.0.html).

(Note, for `GPL-3.0-or-later`, you need to add a notice in, e.g., the README, that you're using the GNU GPL version 3 **or later**.
You can find a plaintext copy of the license at <https://www.gnu.org/licenses/gpl.txt>.)

**Comment by Jorkoh** [comment]
People can legally use it just fine and they already are doing so by downloading the dll within LiveSplit. What they can't do without a explicit license is copy, distribute, or modify the code itself which would only ever be a problem if I decided to go after those that do so. All of this is explained on your own link.

It's pretty clear from the context of this work, a extension of LiveSplit which itself is under a MIT license, that I would never consider enforcing copyright since I wouldn't even be able to. Not like there is anything on this project that could even be copyrighted since the methods used are common knowledge and have already been used by other open source timers. ASL autosplitters and other community contributed components rarely specify a license.

What I'm trying to say is that I will add a license if it ever becomes an issue but for now your message comes across as fear mongering and patronizing. If you _actually_ want to contribute or create derivative work and the lack of a license is _actually_ stopping you feel free to contact me and I will fix it.

**Comment by nfitzen** [comment]
While this reply is months after the fact, I'm still interested in contributing.

I'm sorry for coming off as fearmongering and patronizing. I hope you'll forgive me for that.
My wording and tone could've been better.

In retrospect, I should've mentioned that I intended to hack on the code and potentially contribute. At the time, I was basically intending on implementing <https://github.com/Jorkoh/LiveSplit.Minecraft/commit/0a1ed17b1e01a1372f66754a85947869689c49b4>.

I noticed that you added a [CC0] license to [LiveSplit.Minecraft.Mod](/Jorkoh/LiveSplit.Minecraft.Mod), and I feel like the main component should be public domain as well. Explicit license grants are always better than relying on exceptions to copyright, and applying CC0 in this case can only be beneficial, not harmful.

[CC0]: https://www.creativecommons.org/publicdomain/zero/1.0/
